services:
  app:
    build: ./frontend
    volumes:
      - ./frontend:/front
      - /front/node_modules
      - /front/.next
    ports:
      - 3001:3000
    environment:
      BACKEND_URL: http://api:8000

  api:
    build: ./backend 
    volumes: 
      - ./backend:/backend
    working_dir: /backend
    ports: 
      - 8000:8000 
    env_file:
      - ./backend/.env 
    command: sh -lc "php artisan serve --host=0.0.0.0 --port=8000"